version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    volumes:
      - ./liquibase/changelog-master.yaml:/liquibase/changelog-master.yaml:ro
      - ./liquibase/changelog-1-create_tables.yaml:/liquibase/changelog-1-create_tables.yaml:ro
      - ./liquibase/changelog-2-add_test_data.yaml:/liquibase/changelog-2-add_test_data.yaml:ro
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties:ro
      - ./liquibase/postgresql-42.6.2.jar:/liquibase/postgresql.jar:ro
    entrypoint: ["liquibase", "--defaultsFile=/liquibase/liquibase.properties", "update"]

  python_app:
    build: ./python_app
    depends_on:
      - postgres
      - liquibase
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    command: ["python", "app.py"]
